const projects = [
    {
        name: 'Fruit Collector',
        description: 'It is a game in which a farmer collects fruits falling from the sky. It was made while learning the Junior Programmer Pathway. Built with Unity and C#.',
        image: './images/fruitcollector.png',
        technologies: [
            'C#',
            'Unity',
            '3D',
        ],
        liveVersionLink: 'https://play.unity.com/en/games/4069370b-b5ab-435c-bc65-9b2be53aa789/fruit-collector',
        SourceLink: 'https://github.com/SnakyMz/Counting-Prototype',
        company: 'Freelance',
        year: '2024',
        stack: 'Unity Game Dev',
    },
    {
        name: 'Clicky Stuff',
        description: 'It is a clicking game where you avoid clicking bombs and click pieces of stuff to gain a score. It was made while learning the Junior Programmer Pathway. Built with Unity and C#.',
        image: './images/clickystuff.png',
        technologies: [
            'C#',
            'Unity',
            '3D',
        ],
        liveVersionLink: 'https://play.unity.com/en/games/3b8b4558-c36b-462b-824e-6ace754f9f01/clicky-stuff',
        SourceLink: 'https://github.com/SnakyMz/Game-Prototype-5',
        company: 'Freelance',
        year: '2024',
        stack: 'Unity Game Dev',
    },
    {
        name: 'Rolling Falls',
        description: 'It is a marbles game where you tackle enemy marbles to make them fall and avoid falling yourself. Made while learning Unity Junior Programmer Pathway. Built with Unity and C#.',
        image: './images/rollingfalls.png',
        technologies: [
            'C#',
            'Unity',
            '3D',
        ],
        liveVersionLink: 'https://play.unity.com/en/games/e4289ee3-72c7-4377-b244-e7b5e8682330/rolling-falls',
        SourceLink: 'https://github.com/SnakyMz/Game-Prototype-3',
        company: 'Freelance',
        year: '2024',
        stack: 'Unity Game Dev',
    },
    {
        name: 'City Jumper',
        description: 'It is a game where you avoid obstacles in an endless run. Made while learning Unity Junior Programmer Pathway. Built with Unity and C#.',
        image: './images/cityjumper.png',
        technologies: [
            'C#',
            'Unity',
            '3D',
        ],
        liveVersionLink: 'https://play.unity.com/en/games/6ecd4c4c-28ca-4c82-b29e-c83b6b933a68/city-jumper',
        SourceLink: 'https://github.com/SnakyMz/Game-Prototype-3',
        company: 'Freelance',
        year: '2024',
        stack: 'Unity Game Dev',
    },
    {
        name: 'Cookie Feeder',
        description: 'It is a game where you throw cookies at wild animals and feed them. Made while learning the Unity Junior Programmer Pathway. Built with Unity and C#.',
        image: './images/cookiefeeder.png',
        technologies: [
            'C#',
            'Unity',
            '3D',
        ],
        liveVersionLink: 'https://play.unity.com/en/games/54132f5c-aa67-46ea-ba60-f8662a17aff2/cookie-feeder',
        SourceLink: 'https://github.com/SnakyMz/Game-Prototype-2',
        company: 'Freelance',
        year: '2024',
        stack: 'Unity Game Dev',
    },
    {
        name: 'TestRide',
        description: 'It is a game where you can test - ride a plane or a car.Made while learning Unity Junior programmer Pathway. Built with Unity and C#.',
        image: './images/testride.png',
        technologies: [
            'C#',
            'Unity',
            '3D',
        ],
        liveVersionLink: 'https://play.unity.com/en/games/fd2786c7-a7dd-4997-a4b2-8de528d9eef7/testride',
        SourceLink: 'https://github.com/SnakyMz/Game-Prototype-1',
        company: 'Freelance',
        year: '2024',
        stack: 'Unity Game Dev',
    },
    {
        name: 'Sampler',
        description: 'My first Unity project made while learning the Unity Essentials pathway. It contains 2D gameplay and 3D gameplay of controlling a car while moving around in a living room with it. Built with Unity and C#.',
        image: './images/sampler.png',
        technologies: [
            'C#',
            'Unity',
            '3D',
            '2D',
        ],
        liveVersionLink: 'https://play.unity.com/en/games/758a6f00-02b1-47b7-bd3a-5dd03376ecb2/sampler',
        SourceLink: null,
        company: 'Freelance',
        year: '2024',
        stack: 'Unity Game Dev',
    },
];

export default projects;
