const projects = [
  {
    name: 'Gamecon',
    description: 'An informative website about a Gaming fair called Gamecon. This website is inspired by Cindy Shin`s CC Global Summit 2015. Built with JavaScript.',
    image: './images/gamecon.png',
    technologies: [
      'HTML',
      'CSS',
      'JavaScript',
    ],
    liveVersionLink: 'https://snakymz.github.io/Gamecon/',
    SourceLink: 'https://github.com/SnakyMz/Gamecon',
    company: 'Freelance',
    year: '2023',
    stack: 'Front End Dev',
  },
  {
    name: 'To Do List',
    description: 'A website to keep track of your daily tasks by allowing users to add, remove or update their tasks. Built with JavaScript.',
    image: './images/todolist.png',
    technologies: [
      'HTML',
      'CSS',
      'JavaScript',
    ],
    liveVersionLink: 'https://snakymz.github.io/To-Do-List/',
    SourceLink: 'https://github.com/SnakyMz/To-Do-List',
    company: 'Freelance',
    year: '2023',
    stack: 'Front End Dev',
  },
  {
    name: 'PokeDex',
    description: 'A website that displays a list of Pokemons by fetching data from the API. The website allows users to like and comment on displayed Pokemon which also uses API to maintain data. Built with JavaScript.',
    image: './images/pokedex.png',
    technologies: [
      'HTML',
      'CSS',
      'JavaScript',
      'API',
    ],
    liveVersionLink: 'https://snakymz.github.io/PokeDex/',
    SourceLink: 'https://github.com/SnakyMz/PokeDex',
    company: 'Freelance',
    year: '2023',
    stack: 'Front End Dev',
  },
  {
    name: 'Math Magicians',
    description: 'A website that contains a calculator to perform mathematical operations and a quote section that generates a random quote on load. Built with React.',
    image: './images/mathmagician.png',
    technologies: [
      'HTML',
      'CSS',
      'JavaScript',
      'React',
      'API',
    ],
    liveVersionLink: 'https://math-magicians-7hio.onrender.com/',
    SourceLink: 'https://github.com/SnakyMz/Math-Magicians',
    company: 'Freelance',
    year: '2023',
    stack: 'Front End Dev',
  },
  {
    name: 'Bookstore',
    description: 'A website that contains a library of books. You can add or delete a book. Uses bookstore API to communicate with data. Built with React and Redux.',
    image: './images/bookstore.png',
    technologies: [
      'HTML',
      'CSS',
      'JavaScript',
      'React',
      'Redux',
      'API',
    ],
    liveVersionLink: 'https://bookstore-kn2l.onrender.com/',
    SourceLink: 'https://github.com/SnakyMz/Bookstore',
    company: 'Freelance',
    year: '2023',
    stack: 'Front End Dev',
  },
  {
    name: 'Space Travellers Hub',
    description: 'A website that displays rockets and missions from SpaceX. It also allows user to reserve any rocket/mission and displays them in the My Profile section. Built with React and Redux.',
    image: './images/spacehub.png',
    technologies: [
      'HTML',
      'CSS',
      'JavaScript',
      'React',
      'Redux',
      'API',
    ],
    liveVersionLink: 'https://space-travellers-hub-y40g.onrender.com/',
    SourceLink: 'https://github.com/SnakyMz/Space-Travellers-Hub',
    company: 'Freelance',
    year: '2023',
    stack: 'Front End Dev',
  },
  {
    name: 'Karnataka Weather',
    description: 'A website that displays a list of cities. It also displays their respective temperature, weather status, and many more. Built with React and Redux.',
    image: './images/karnatakaweather.png',
    technologies: [
      'HTML',
      'CSS',
      'JavaScript',
      'React',
      'Redux',
      'API',
    ],
    liveVersionLink: 'https://karnataka-weather.onrender.com/',
    SourceLink: 'https://github.com/SnakyMz/Karnataka-weather',
    company: 'Freelance',
    year: '2023',
    stack: 'Front End Dev',
  },
  {
    name: 'Recipe App',
    description: 'Recipe App is a app containing data about foods, recipes, and shopping lists. Built with Ruby on Rails and Tailwind.',
    image: './images/recipeapp.png',
    technologies: [
      'HTML',
      'Tailwind CSS',
      'Ruby on Rails',
    ],
    liveVersionLink: 'https://recipe-app-t2ko.onrender.com/',
    SourceLink: 'https://github.com/JavierAybar/Recipe-app',
    company: 'Freelance',
    year: '2023',
    stack: 'Full Stack Dev',
  },
  {
    name: 'Expense App',
    description: 'Expense App is an transaction tracker app containing data about transactions based on categories. A user can register/login and create transactions to track them. Built with Ruby on Rails.',
    image: './images/expenseapp.png',
    technologies: [
      'HTML',
      'CSS',
      'Ruby on Rails',
    ],
    liveVersionLink: 'https://expense-app-i6s3.onrender.com/',
    SourceLink: 'https://github.com/SnakyMz/Expense-app',
    company: 'Freelance',
    year: '2023',
    stack: 'Full Stack Dev',
  },
  {
    name: 'Appoint Wheels',
    description: 'AppointWheels is a car rental application that allows users to book a car for a specific date and time. Users can create an account and log in to the application. Built with React, Redux and Ruby on Rails.',
    image: './images/appointwheels.png',
    technologies: [
      'HTML',
      'JavaScript',
      'React',
      'Redux',
      'Tailwind CSS',
      'Ruby on Rails',
    ],
    liveVersionLink: 'https://appointwheels.onrender.com/',
    SourceLink: 'https://github.com/Rysth/REACT-AppointWheels',
    company: 'Freelance',
    year: '2023',
    stack: 'Full Stack Dev',
  },
];

export default projects;
